parameters:
  # Adds a fallback DATABASE_URL if the env var is not set. This allows you
  # to run cache:warmup even if your environment variables are not available
  # yet. You should not need to change this value.
  env(DATABASE_URL): ''

doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Seat/Infrastructure/Symfony4/Doctrine'
        prefix: 'Symfony4\Doctrine'

    dql:
      string_functions:
        cast:           Oro\ORM\Query\AST\Functions\Cast
